### ISSUE TITLE
Submission limit and team creation

### ISSUE THREAD

**Issue by shaido987** [iarai/NeurIPS2022-traffic4cast#14]
Hello,

When trying to create a submission on the competition page there is a notice saying that there is a maximum of 5 submissions per team or participant. So we can only make a total of 5 submissions during the whole competition time? Is the test data in the online submission the same as the recently released test data?

Also, how are the teams created? The submission page has a "team password" that should be related somehow?

**Comment by chenkins** [comment]
@shaido987 
> When trying to create a submission on the competition page there is a notice saying that there is a maximum of 5 submissions per team or participant. So we can only make a total of 5 submissions during the whole competition time? 

You can delete your submissions to make space for further submissions - you can only have 5 submissions in the leaderboard. 

> Is the test data in the online submission the same as the recently released test data?

Yes, `Tests for the core competition are contained in T4C_INPUTS_2022.zip above.` see https://github.com/iarai/NeurIPS2022-traffic4cast#download-links.

> Also, how are the teams created? The submission page has a "team password" that should be related somehow?

Enter a team name and password the first time and then re-use the same afterwards. Will forward this to our UI team.

**Comment by shaido987** [comment]
I see, no need to worry about spending the submissions early on then. Thanks for the quick response!

**Comment by chenkins** [comment]
Keeping this open to track the progress in the UI.

**Comment by chenkins** [comment]
Done: 
![image](https://user-images.githubusercontent.com/22786861/187138959-8a612edc-cd9a-4dd5-8522-71b4a28b05b0.png)
