### ISSUE TITLE
how to download T4C_INPUTS_2022.zip ? I found that I can't download it from the link.

### ISSUE THREAD

**Issue by yizhicainiao2022** [iarai/NeurIPS2022-traffic4cast#16]

**Comment by chenkins** [comment]
@yizhicainiao2022 can you add more information? Download from http://iarai-public.s3-eu-west-1.amazonaws.com/competitions/t4c/t4c22/T4C_INPUTS_2022.zip works for me.

**Comment by yizhicainiao2022** [comment]
OK, I can download it from your link. Think you.

**Comment by yizhicainiao2022** [comment]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/109080676/186943583-ab0e2eb7-6e8f-4efa-a47f-2735facc035a.png">

**Comment by yizhicainiao2022** [comment]
This link doesn't work.

**Comment by chenkins** [comment]
@yizhicainiao2022 which browser did you use?

**Comment by chenkins** [comment]
@yizhicainiao2022 can you check again? It should be fixed now.

**Comment by yizhicainiao2022** [comment]
@chenkins It can be accessed now. Thanks.

**Comment by MikeDean2367** [comment]
Hi, this link doesn't work. Could you please offer the accessible link for `T4C_INPUTS_2022.zip` and `T4C_INPUTS_ETA_2022.zip`?
