### ISSUE TITLE
Unable to make submissions

### ISSUE THREAD

**Issue by vishalmhjn** [iarai/NeurIPS2022-traffic4cast#19]
I am faced with uploading being stuck at 100%. I tried different browsers, etc., but the issue remains. The zipped filesize for the core competition is around 600 MB, which I hope should not be a problem. Please see the screenshot.

Thanks for your support.

<img width="1255" alt="Screen Shot 2022-09-09 at 6 40 16 PM" src="https://user-images.githubusercontent.com/42190624/189357662-eaef5c82-1eff-4201-91ae-5445a5d14481.png">

**Comment by vishalmhjn** [comment]
I tried after clearing the cookies and cache. Below are a few screenshots from the Network tab. It seems no data is being transferred. I hope this could help to track the problem.
Preview:
<img width="794" alt="Screen Shot 2022-09-09 at 8 06 57 PM" src="https://user-images.githubusercontent.com/42190624/189375573-12a66632-75ec-497f-8bfd-99da0ad17bc7.png">


<img width="1021" alt="Screen Shot 2022-09-09 at 8 04 34 PM" src="https://user-images.githubusercontent.com/42190624/189375577-2d8c1a25-6e69-485a-a51e-73c5caf286d5.png">

**Comment by moritz9** [comment]
Hi @vishalmhjn also just verified with a 750MB file that the submission is working. The call to admin-ajax.php should return with HTTP code 200 even if your submission fails or you're not logged in. Are you behind a proxy or a VPN which might affecting your internet traffic?

**Comment by vishalmhjn** [comment]
No, I am not using either.

**Comment by vishalmhjn** [comment]
Thanks again for your support. As suggested, I tested it with a dummy zip file, and it worked. Then I also tested it with a manually compressed submission file, and it works fine now. 
Since I was using the official code below for creating the zipped files, I found that compression using the following is [not actually compressing it](https://stackoverflow.com/questions/4166447/python-zipfile-module-doesnt-seem-to-be-compressing-my-files), leading to the submission failure. 
https://github.com/iarai/NeurIPS2022-traffic4cast/blob/5b8c66817e0dda6c204552835b5978c0facc6853/t4c22/evaluation/create_submission.py#L151  
If this is indeed the case with not just me, maybe the compression method in above code could be changed.
I think this issue can be closed now.

**Comment by chenkins** [comment]
@vishalmhjn thanks for your answer! As the `.parquet` files  are already compressed, we did not add compression when zipping in the first place. I've just re-tested the zip file and upload creation using `create_submission.py`. Which browser/OS do you use? Your browser might send a non-accepted MIME type in the request, see e.g.
https://stackoverflow.com/questions/856013/mime-type-for-zip-file-in-google-chrome
Could you check the MIME type in your browser for the failing submission? In my browser (ff on Linux), it looks as follows for a "stored-only" submission:
![image](https://user-images.githubusercontent.com/22786861/190096861-80d882a1-736e-4ce3-9d64-ecf8be059e8e.png)
If that's the culprit, we can then add the compression while the `zipfile` lines as suggested by you above and add the MIME type to word press as well as fix. Thanks for your collaboration!

**Comment by chenkins** [comment]
#20

**Comment by vishalmhjn** [comment]
Thanks again. I remember facing this issue on OSX (safari) and Ubuntu (ff, gc). With the DEFLATED compression, this is not a problem on my system anymore. 

here is the screenshot  for MIME type, which looks fine:
<img width="428" alt="Screen Shot 2022-09-16 at 12 57 16 PM" src="https://user-images.githubusercontent.com/42190624/190581414-69910f5b-95e6-4262-a531-7c891806fd15.png">

**Comment by chenkins** [comment]
@vishalmhjn thinks for the update and inputs.
